server:
  port: 8888

spring:
  application:
    name: eteryz-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eteryz/spring-example.git
          clone-on-start: true
          default-label: spring-cloud-config
          search-paths:
            - './config/cloud'

# берем конфиги из гита