version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: feedback-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - feedback-network

volumes:
  mongo_data:

networks:
  feedback-network:
    driver: bridge
